package com.flowerfat.makepoint.sqlite;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.flowerfat.makepoint.sqlite.Point;
import com.flowerfat.makepoint.sqlite.Note;

import com.flowerfat.makepoint.sqlite.PointDao;
import com.flowerfat.makepoint.sqlite.NoteDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig pointDaoConfig;
    private final DaoConfig noteDaoConfig;

    private final PointDao pointDao;
    private final NoteDao noteDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        pointDaoConfig = daoConfigMap.get(PointDao.class).clone();
        pointDaoConfig.initIdentityScope(type);

        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        pointDao = new PointDao(pointDaoConfig, this);
        noteDao = new NoteDao(noteDaoConfig, this);

        registerDao(Point.class, pointDao);
        registerDao(Note.class, noteDao);
    }
    
    public void clear() {
        pointDaoConfig.getIdentityScope().clear();
        noteDaoConfig.getIdentityScope().clear();
    }

    public PointDao getPointDao() {
        return pointDao;
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }

}
